name: measure

on: [push, pull_request]

jobs:
  measure:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        M: [1, 2]
        D: [100, 1000, 2000]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: pypy-3.6

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: actions/cache@v2
      id: cache-tools
      with:
        path: tools/
        key: ${{ runner.os }}-tools-ahc003

    - name: Prepare tools/
      if: steps.cache-tools.outputs.cache-hit != 'true'
      run: |
        wget https://img.atcoder.jp/ahc003/c1ae4a8996958aa31f5f9d3aa3f51033.zip
        unzip c1ae4a8996958aa31f5f9d3aa3f51033.zip

    - name: Build the visualizer
      run: |
        cargo build --manifest-path=tools/Cargo.toml --release

    - name: Compile the code
      run: |
        g++ -std=c++17 -Wall -O2 -Iac-library -DLOCAL main.cpp

    - name: Measure the score
      run: |
        pypy3 scripts/measure.py --jobs 2 --count 100 -M ${{ matrix.M }} -D ${{ matrix.D }}
